import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getPublicOrderStatus } from "@/lib/storefront";
import { Search, Truck } from "lucide-react";

const labels: Record<string, string> = { submitted: "تم استلام الطلب", under_review: "قيد المراجعة", needs_info: "محتاج بيانات", accepted: "تم قبول الطلب", invoiced: "تم إنشاء الفاتورة", shipped: "تم الشحن", delivered: "تم التسليم", rejected: "تعذر قبول الطلب", cancelled: "تم إلغاء الطلب", expired: "انتهت مهلة الحجز" };
export default function OrderTracking() {
  const [number, setNumber] = useState(""); const [phone, setPhone] = useState(""); const [result, setResult] = useState<Awaited<ReturnType<typeof getPublicOrderStatus>>>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const search = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); setResult(null); try { const order = await getPublicOrderStatus(number, phone); if (!order) setError("مش لاقيين طلب بالبيانات دي"); else setResult(order); } catch { setError("حصلت مشكلة، جرب تاني"); } finally { setBusy(false); } };
  return <main dir="rtl" className="min-h-screen bg-[#07110e] px-4 py-16 text-white"><div className="mx-auto max-w-lg"><div className="text-center"><Truck className="mx-auto h-10 w-10 text-emerald-300" /><h1 className="mt-4 text-3xl font-black">تتبع طلبك</h1><p className="mt-2 text-slate-400">اكتب رقم الطلب ورقم الموبايل المسجل.</p></div><form onSubmit={search} className="mt-8 grid gap-4 rounded-3xl border border-white/10 bg-white/[.04] p-6"><Input value={number} onChange={(event) => setNumber(event.target.value)} placeholder="رقم الطلب" required className="border-white/10 bg-white/5 text-white" /><Input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="رقم الموبايل" required className="border-white/10 bg-white/5 text-white" /><Button disabled={busy}>{busy ? "جاري البحث..." : <><Search className="h-4 w-4" /> بحث</>}</Button></form>{error && <p className="mt-5 rounded-2xl bg-rose-400/10 p-4 text-center text-rose-300">{error}</p>}{result && <section className="mt-5 rounded-3xl border border-emerald-300/15 bg-emerald-300/5 p-6"><p className="text-sm text-slate-400">طلب رقم {result.public_number}</p><h2 className="mt-2 text-2xl font-black text-emerald-300">{labels[result.status] ?? result.status}</h2><p className="mt-4 text-lg font-bold">الإجمالي: {new Intl.NumberFormat("ar-EG").format(result.total)} ج.م</p><div className="mt-4 grid gap-2 text-sm text-slate-300">{result.items.map((item) => <div key={item.title}>{item.title} × {item.quantity}</div>)}</div></section>}</div></main>;
}
