import { useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { BezelCard } from "@/components/BezelCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { getMyStorefront, saveStorefront, type Storefront } from "@/lib/storefront";
import { addStorefrontDomain, getStorefrontDomains, type StorefrontDomain } from "@/lib/storefront-domains";
import { Globe2, Loader2, Palette, Save, Store } from "lucide-react";
import { toast } from "sonner";

export default function StorefrontSettings() {
  const [shop, setShop] = useState<Storefront | null>(null); const [form, setForm] = useState({ banner_url: "", theme_key: "emerald", seo_title: "", seo_description: "", minimum_order: "0", facebook: "", instagram: "", whatsapp: "" }); const [domain, setDomain] = useState(""); const [domains, setDomains] = useState<StorefrontDomain[]>([]); const [busy, setBusy] = useState(true);
  useEffect(() => { (async () => { try { const value = await getMyStorefront(); setShop(value); if (value) { setForm({ banner_url: value.banner_url ?? "", theme_key: value.theme_key ?? "emerald", seo_title: value.seo_title ?? "", seo_description: value.seo_description ?? "", minimum_order: String(value.minimum_order ?? 0), facebook: value.social_links?.facebook ?? "", instagram: value.social_links?.instagram ?? "", whatsapp: value.social_links?.whatsapp ?? "" }); setDomains(await getStorefrontDomains(value.id)); } } catch (error: any) { toast.error(error.message ?? "تعذر تحميل الإعدادات"); } finally { setBusy(false); } })(); }, []);
  const save = async () => { if (!shop) return; try { const value = await saveStorefront({ ...shop, ...form, minimum_order: Number(form.minimum_order) || 0, social_links: { facebook: form.facebook, instagram: form.instagram, whatsapp: form.whatsapp } }); setShop(value); toast.success("اتحفظت إعدادات المتجر"); } catch (error: any) { toast.error(error.message ?? "تعذر الحفظ"); } };
  const addDomain = async () => { if (!shop || !domain.trim()) return; try { const value = await addStorefrontDomain(shop.id, domain); setDomains((current) => [value, ...current]); setDomain(""); toast.success("اتضاف الدومين، أكمل التحقق من DNS"); } catch (error: any) { toast.error(error.message ?? "تعذر إضافة الدومين"); } };
  if (busy) return <AppShell><div className="grid min-h-[50vh] place-items-center"><Loader2 className="h-8 w-8 animate-spin" /></div></AppShell>;
  return <AppShell><div dir="rtl" className="space-y-6 pb-20"><PageHeader title="إعدادات المتجر" subtitle="الهوية والظهور والدومين المخصص." icon={<Store className="h-7 w-7" />} /><div className="grid gap-5 lg:grid-cols-2"><BezelCard className="p-6"><div className="flex items-center gap-2"><Palette className="h-5 w-5 text-primary" /><h2 className="font-bold">الهوية والظهور</h2></div><div className="mt-5 grid gap-4"><Field label="رابط البانر" value={form.banner_url} onChange={(banner_url) => setForm({ ...form, banner_url })} /><div><Label>الثيم</Label><select value={form.theme_key} onChange={(event) => setForm({ ...form, theme_key: event.target.value })} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3"><option value="emerald">Emerald</option><option value="copper">Copper</option><option value="blue">Blue</option></select></div><Field label="الحد الأدنى للطلب" value={form.minimum_order} onChange={(minimum_order) => setForm({ ...form, minimum_order })} /><Field label="عنوان SEO" value={form.seo_title} onChange={(seo_title) => setForm({ ...form, seo_title })} /><div><Label>وصف SEO</Label><Textarea value={form.seo_description} onChange={(event) => setForm({ ...form, seo_description: event.target.value })} className="mt-2" /></div><Field label="Facebook" value={form.facebook} onChange={(facebook) => setForm({ ...form, facebook })} /><Field label="Instagram" value={form.instagram} onChange={(instagram) => setForm({ ...form, instagram })} /><Field label="WhatsApp" value={form.whatsapp} onChange={(whatsapp) => setForm({ ...form, whatsapp })} /></div><Button className="mt-5" onClick={() => void save()}><Save className="h-4 w-4" /> حفظ الإعدادات</Button></BezelCard><BezelCard className="p-6"><div className="flex items-center gap-2"><Globe2 className="h-5 w-5 text-primary" /><h2 className="font-bold">الدومين المخصص</h2></div><div className="mt-5 flex gap-2"><Input value={domain} onChange={(event) => setDomain(event.target.value)} placeholder="shop.example.com" dir="ltr" /><Button onClick={() => void addDomain()}>إضافة</Button></div><div className="mt-5 grid gap-2">{domains.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl bg-muted/35 p-3 text-sm"><span dir="ltr">{item.domain}</span><span className="text-muted-foreground">{item.status === "active" ? "نشط" : "في انتظار DNS"}</span></div>)}</div></BezelCard></div></div></AppShell>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div><Label>{label}</Label><Input value={value} onChange={(event) => onChange(event.target.value)} className="mt-2" /></div>; }
